---
es_user: elasticsearch
es_group: elasticsearch
es_data_dir: "{{ rock_data_dir }}/elasticsearch"
es_cluster_name: rocknsm
es_node_name: "{{ inventory_hostname }}"
es_network_host: >-
  {%- if (groups['elasticsearch']|union(groups['logstash'])|union(groups['kibana']))| count > 1 -%}
  _site:ipv4_
  {%- else -%}
  _local:ipv4_
  {%- endif -%}
es_interface: >-
    {%- if (groups['elasticsearch']|union(groups['logstash'])|union(groups['kibana']))| count > 1 -%}
    {{ ansible_hostname }}
    {%- else -%}
    localhost
    {%- endif -%}
es_action_auto_create_index: true
es_min_master_nodes: "{{ 2 if ( groups['es_masters'] | length ) == 3 else 1 }}"
es_mem: "{{ (ansible_memtotal_mb // 1024 // 2) if (ansible_memtotal_mb // 1024) < 64 else 31 }}"
es_url: "http://127.0.0.1:9200"
es_log_dir: /var/log/elasticsearch
es_memlock_override: |
  [Service]
  LimitMEMLOCK=infinity
