apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: default
  labels:
    component: elk
    role: kibana
spec:
  selector:
    component: elk
    role: kibana
  ports:
  - name: http
    port: 80
    targetPort: 5601
    protocol: TCP
