apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: default
  labels:
    component: elk
    role: logstash
spec:
  selector:
    component: elk
    role: logstash
  ports:
  - name: lumberjack
    port: 5043
    protocol: TCP
