---
- name: Copy deploy file
  template:
    src: templates/deploy.yml.j2
    dest: "{{ ceph_dir }}/deploy.yml"
    owner: root
    group: root
    mode: 0644

- name: Flush provisioner
  command: "kubectl delete -f {{ ceph_dir }}/deploy.yml --ignore-not-found=true"

- name: Deploy Services
  import_role:
    name: kubernetes/common
    tasks_from: kube_create.yml
  vars:
    name: "Ceph Provisioner"
    file_name: "{{ ceph_dir }}/deploy.yml"

- name: Wait for ceph provisioner to be ready
  import_role:
    name: kubernetes/common
    tasks_from: kube_wait
  vars:
    type: "pods"
    namespace: "kube-system"
    resource_name: ""
    label: "app=rbd-provisioner"
