---

- include_tasks: preflight.yml

- name: Fail if ceph unhealthy
  fail: 
    msg: "Ceph health check failed.  Stopping play. Error: {{ ceph_status_result }}"
  when: (kube_check_result is defined and kube_check_result.stdout == "") 
     or "(ceph_status_result is defined and 'HEALTH_ERR' in ceph_status_result.stdout)"
