---

- name: Wait for Ceph to normalize
  shell: |
    TIMEOUT=200
    COUNT=0
    while [ "$(ceph health)" != "HEALTH_OK" ]; do \
      echo -n .;
      sleep 1;
      COUNT=$((COUNT + 1))
      if [ $COUNT -ge $TIMEOUT ];
      then
        break;
      fi;
    done;

- name: Get Ceph Health
  shell:  ceph health
  register: ceph_status_result
  failed_when: ceph_status_result.rc != 127 and ceph_status_result.rc != 0 and ceph_status_result.rc != 1

- name: Fail if ceph unhealthy
  fail:
    msg: "Ceph health check failed.  Stopping play. Error: {{ ceph_status_result }}"
  when: "(ceph_status_result is defined and 'HEALTH_ERR' in ceph_status_result.stdout) or (ceph_status_result is defined and 'HEALTH_WARN' in ceph_status_result.stdout and node_to_add is not defined)"

...
