######################################################
################## Setup Suricata ####################
######################################################
---

-
  name: Install Suricata package
  yum:
    name: suricata
    state: installed
-
  name: Create Suricata directories
  file:
    path: "{{ suricata_data_dir }}/"
    mode: 0755
    owner: "{{ suricata_user }}"
    group: "{{ suricata_group }}"
    state: directory
  when: with_suricata

-
  name: Set suricata capabilities
  capabilities:
    path: /usr/sbin/suricata
    capability: "{{ item }}"
    state: present
  with_items:
    - "cap_net_raw+eip"
    - "cap_net_admin+eip"
    - "cap_ipc_lock+eip"
  when: with_suricata

-
  name: Remove suricata sysconfig file
  file:
    path: /etc/sysconfig/suricata
    state: absent
  when: with_suricata

- 
  name: Install suricata service files
  copy:
    src: "suricata.service"
    dest: "/etc/systemd/system/suricata.service"
    mode: 0644
    owner: root
    group: root
  when: with_suricata

- 
  name: Install suricata overrides
  template:
    src: templates/suricata_overrides.yaml.j2
    dest: /etc/suricata/rocknsm-overrides.yaml
    mode: 0644
    owner: "{{ suricata_user }}"
    group: root
  when: with_suricata

-
  name: Create IP reputation config dir
  file:
    path: /etc/suricata/rules/iplists
    state: directory
    owner: root
    group: root
    mode: 0755
  when: with_suricata

-
  name: Set suricata overrides include in main config
  lineinfile:
    dest: /etc/suricata/suricata.yaml
    line: "include: rocknsm-overrides.yaml"
    state: present
  when: with_suricata

-
  name: Enable and start suricata
  service:
    name: suricata
    enabled: "{{ enable_suricata }}"
    state: "{{ 'started' if enable_suricata else 'stopped' }}"
  when: with_suricata

-
  name: Configure logrotate for suricata logs
  template:
    src: templates/logrotate-suricata.conf.j2
    dest: /etc/logrotate.d/suricata.conf
    mode: 0644
    owner: root
    group: root
  when: with_suricata