######################################################
################## Setup Suricata ####################
######################################################
---

- name: Install Suricata package
  yum:
    name: suricata
    state: installed

- name: Create Suricata directories
  file:
    path: "{{ suricata_data_dir }}/"
    mode: 0755
    owner: "{{ suricata_user }}"
    group: "{{ suricata_group }}"
    state: directory

- name: Set suricata capabilities
  capabilities:
    path: /usr/sbin/suricata
    capability: "{{ item }}"
    state: present
  with_items:
    - "cap_net_raw+eip"
    - "cap_net_admin+eip"
    - "cap_ipc_lock+eip"

- name: Remove suricata sysconfig file
  file:
    path: /etc/sysconfig/suricata
    state: absent
 
- name: Install suricata service files
  copy:
    src: "suricata.service"
    dest: "/etc/systemd/system/suricata.service"
    mode: 0644
    owner: root
    group: root
 
- name: Install suricata overrides
  template:
    src: templates/suricata_overrides.yaml.j2
    dest: /etc/suricata/rocknsm-overrides.yaml
    mode: 0644
    owner: "{{ suricata_user }}"
    group: root

- name: Create IP reputation config dir
  file:
    path: /etc/suricata/rules/iplists
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Set suricata overrides include in main config
  lineinfile:
    dest: /etc/suricata/suricata.yaml
    line: "import_tasks: rocknsm-overrides.yaml"
    state: present

- name: Enable and start suricata
  service:
    name: suricata
    enabled: yes
    state: started

- name: Configure logrotate for suricata logs
  template:
    src: templates/logrotate-suricata.conf.j2
    dest: /etc/logrotate.d/suricata.conf
    mode: 0644
    owner: root
    group: root