---

- name: "Setup ROCK NSM repo"
  yum_repository:
    baseurl: "{{ rocknsm_baseurl }}"
    cost: 750
    description: "ROCK NSM repository for devel"
    gpgcheck: false
    gpgkey: "{{ rocknsm_gpgurl }}"
    name: rocknsm
  tags: 'repo'
