#######################################################
################## Setup Yum Repos ####################
#######################################################
---

- name: Check presence of fastestmirror.conf
  stat:
    path: /etc/yum/pluginconf.d/fastestmirror.conf
  register: fastestmirror

# fastestmirror plugin actually slows down Ansible deployments
- name: Disable fastestmirror plugin
  lineinfile:
    dest: /etc/yum/pluginconf.d/fastestmirror.conf
    regexp: "^enabled=.*"
    line: "enabled=0"
    state: present
  when: fastestmirror.stat.exists and ansible_distribution == 'CentOS'

- name: Setup Deployer offline repo
  yum_repository:
    baseurl: "http://deployer.lan/centos/$releasever/offline/$basearch"
    cost: 500
    description: "Deployer Repository"
    gpgcheck: false
    name: Deployer-local
  when: "not online_install"

- name: Install EPEL release
  yum:
    name: epel-release
    state: installed
  when: online_install

#- name: "Setup EPEL repo"
#  yum_repository:
#    baseurl: "{{ epel_baseurl }}"
#    description: "EPEL YUM repo"
#    gpgcheck: true
#    gpgkey: "{{ epel_gpgurl }}"
#    mirrorlist: "https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch"
#    name: epel
#  when: rock_online_install

#- name: "Manually trust CentOS GPG key"
#  shell: "rpm --import http://mirror.centos.org/centos/RPM-GPG-KEY-CentOS-7\n"
#  when: "rock_online_install and ansible_distribution == \"CentOS\""

- name: "Configure default CentOS online repos"
  yum_repository:
    description: "CentOS-$releasever - {{ item.name | title }}"
    enabled: "{{ online_install }}"
    file: CentOS-Base
    mirrorlist: "{{ item.mirror }}"
    name: "{{ item.name }}"
  with_items:
  - { name: base, mirror: "http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=os&infra=$infra" }
  - { name: updates, mirror: "http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=updates&infra=$infra" }
  - { name: extras, mirror: "http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=extras&infra=$infra"}
  when: "ansible_distribution == \"CentOS\""


