---

- name: 'Install Docker package'
  yum:
    name: docker
    state: 'installed'

- name: 'Patch outstanding bug'
  file:
    src: /usr/libexec/docker/docker-runc-current
    dest: /usr/libexec/docker/docker-runc
    owner: root
    group: root
    state: link

# Allow containers to manage cgroups - needed for systemd init
# This is way safer that running privileged containers
- name: 'Set SELinux Booleans'
  seboolean:
    name: container_manage_cgroup
    state: yes
    persistent: yes
