%YAML 1.1
---

#### Main Role Configuration ####

kafka_container_name: "rocknsm/kafka"
kafka_port: 9092
kafka_ver: latest

kafka_dir: "{{ rocknsm_dir }}/kafka"
kafka_data_dir: "{{ kafka_dir }}/data"

kafka_pv_data: "kafka-data"
kafka_data_path: "/tmp/kafka-logs"
kafka_pv_size: 1

zookeeper_port: 2181
zookeeper_dir: "{{ rocknsm_dir }}/zookeeper"
zookeeper_data_dir: "{{ zookeeper_dir }}/data"
zookeeper_data_path: "/data"
zookeeper_log_dir: '/var/log/zookeeper'
zookeeper_pv_data: "zookeeper-data"
zookeeper_pv_size: 1
zookeeper_container: rocknsm/zookeeper
zookeeper_ver: latest
