%YAML 1.1
---
rock_online_install: true
rock_sysctl_file: /etc/sysctl.d/10-ROCK.conf
rock_data_dir: /data
rocknsm_dir: /opt/rocknsm
rock_data_user: root
rock_data_group: root

rock_hostname: "{{ inventory_hostname_short }}"
rock_fqdn: "{{ inventory_hostname }}"
rock_mgmt_nets: [ "0.0.0.0/0" ]
rock_cache_dir: /srv/rocknsm/support

#### Retention Configuration ####

bro_log_retention: 0
bro_stats_retention: 0
elastic_close_interval: 15
elastic_delete_interval: 60
kafka_retention: 168
suricata_retention: 3


# Feature options - Don't flip these unless you know what you're doing
# These control if the service is installed

with_bro: true
with_docker: true
with_elasticsearch: true
with_filebeat: true
with_fsf: true
with_kafka: true
with_kibana: true
with_logstash: true
with_nginx: true
with_pulledpork: true
with_snort: false
with_stenographer: true
with_suricata: true
with_zookeeper: true

# Feature options - Don't flip these unless you know what you're doing
# These control if the systemd service is enabled

enable_bro: true
enable_docker: true
enable_elasticsearch: true
enable_filebeat: true
enable_fsf: false
enable_kafka: true
enable_kibana: true
enable_logstash: true
enable_nginx: true
enable_pulledpork: true
enable_snort: false
enable_stenographer: false
enable_suricata: true
enable_zookeeper: true

rocknsm_package_list:
  - java-1.8.0-openjdk-headless
  - jq
  - GeoIP
  - GeoIP-update
  - tcpreplay
  - tcpdump
  - bats
  - policycoreutils-python
  - htop
  - vim
  - git
  - tmux
  - nmap-ncat
  - logrotate
  - perl-LWP-Protocol-https
  - perl-Sys-Syslog
  - perl-Crypt-SSLeay
  - perl-Archive-Tar
  - easy-rsa
  
