#######################################################
###################### Setup Bro  #####################
#######################################################
---

- name: Install Bro Package
  yum:
    name: bro
    state: installed
    
- name: Install Bro plugin for af_packet
  yum:
    name: bro-plugin-af_packet
    state: installed
  when: 
  
- name: Install Bro plugin for Kafka
  yum:
    name: bro-plugin-kafka
    state: installed
  when: with_kafka

- name: Create bro group
  group:
    name: "{{ bro_group }}"
    state: present
    system: yes
 
- name: Create bro user and group
  user:
    name: "{{ bro_user }}"
    comment: "bro service account"
    createhome: no
    group: "{{ bro_group }}"
    home: /opt/bro
    shell: /sbin/nologin
    system: yes
    state: present

- name: Create Bro directories
  file:
    path: "{{ item }}"
    mode: 0755
    owner: "{{ bro_user }}"
    group: "{{ bro_group }}"
    state: directory
  with_items:
    - "{{ bro_data_dir }}"
    - "{{ bro_data_dir }}/logs"
    - "{{ bro_data_dir }}/spool"
 
- name: Create symlinks for wandering analysts
  file:
    dest: "/opt/bro/{{ item }}"
    src:  "{{ bro_data_dir }}/{{ item }}"
    state: link
    force: yes
  with_items:
    - logs

- name: Install broctl service file
  template:
    src: templates/broctl.service.j2
    dest: /etc/systemd/system/broctl.service
    owner: root
    group: root
    mode: 0644
  notify: reload systemd
 
- name: Create Bro node.cfg
  template:
    src: templates/bro-node.cfg.j2
    dest: /opt/bro/etc/node.cfg
    mode: 0644
    owner: root
    group: root
  notify: reload broctl
 
- name: Create broctl.cfg
  template:
    src: templates/bro-broctl.cfg.j2
    dest: /opt/bro/etc/broctl.cfg
    mode: 0644
    owner: root
    group: root
  notify: reload broctl

- name: Create bro networks.cfg
  copy:
    src: bro-networks.cfg
    dest: /opt/bro/etc/networks.cfg
    mode: 0644
    owner: root
    group: root
  notify: reload broctl
 
- name: Add bro custom scripts dir
  file:
    path: /opt/bro/share/bro/site/scripts
    owner: root
    group: root
    mode: 0755
    state: directory
 
- name: Set permissions on broctl scripts dir
  file:
    path: /opt/bro/share/broctl/scripts
    owner: "{{ bro_user }}"
    group: "{{ bro_user }}"
    mode: 0755
    state: directory

- name: Add README to scripts dir
  copy:
    src: bro-scripts-readme.txt
    dest: /opt/bro/share/bro/site/scripts/README.txt
    mode: 0644
    owner: root
    group: root

- name: Checkout ROCK Bro scripts
  git:
    repo: "{{ bro_rockscripts_repo }}"
    dest: /opt/bro/share/bro/site/scripts/rock
    version: "{{ bro_rockscripts_branch }}"
  when: rock_online_install

- name: Check for pre-installed Bro script .tar.gz
  stat:
    path: "{{ rock_cache_dir }}/{{ bro_rockscripts_filename }}"
  register: script_check_result

- name: Deploy offline ROCK Bro scripts
  unarchive:
    src: "{{ rock_cache_dir }}/{{ bro_rockscripts_filename }}"
    dest: /opt/bro/share/bro/site/scripts/
    owner: root
    group: root
    creates: "/opt/bro/share/bro/site/scripts/rock-scripts-{{ bro_rockscripts_branch | replace ('/', '-') }}"
    remote_src: yes
  when: not rock_online_install and script_check_result.stat.exists
 
- name: Symlink offline ROCK bro scripts
  file:
    src: "/opt/bro/share/bro/site/scripts/rock-scripts-{{ bro_rockscripts_branch | replace ('/', '-') }}"
    dest: "/opt/bro/share/bro/site/scripts/rock"
    state: link
    force: yes
  when: rock_online_install and script_check_result == True

- name: Update owner for ROCK NSM Bro scripts
  file:
    path: /opt/bro/share/bro/site/scripts/rock
    owner: "{{ bro_user }}"
    group: "{{ bro_group }}"
    state: directory
    recurse: yes
    follow: yes
  tags:
    - bro_scripts

- name: Add ROCK scripts to local.bro
  lineinfile:
    dest: /opt/bro/share/bro/site/local.bro
    line: "@load scripts/rock # ROCK NSM customizations"
    state: present

- name: Add AF_PACKET workaround to local.bro
  lineinfile:
    dest: /opt/bro/share/bro/site/local.bro
    line: "@load scripts/rock/plugins/afpacket"
    state: present

- name: Enable Bro Kafka output to local.bro
  lineinfile:
    dest: /opt/bro/share/bro/site/local.bro
    line: "@load scripts/rock/plugins/kafka"
    state: present
  when: with_kafka

- name: Enable the SMB Analyzer in local.bro
  lineinfile:
    dest: /opt/bro/share/bro/site/local.bro
    line: "@load policy/protocols/smb # Enable Bro SMB Analyzer"
    state: present

- name: Add bro to path and aliases
  copy:
    src: profile.d-bro.sh
    dest: /etc/profile.d/bro.sh
    mode: 0644
    owner: root
    group: root

- name: Add broctl wrapper for admin use
  copy:
    src: broctl.sh
    dest: /usr/sbin/broctl
    mode: 0754
    owner: root
    group: root

- name: Set bro capabilities
  capabilities:
    path: /opt/bro/bin/bro
    capability: "{{ item }}"
    state: present
  with_items:
    - "cap_net_raw+eip"
    - "cap_net_admin+eip"

- name: Set capstats capabilities
  capabilities:
    path: /opt/bro/bin/capstats
    capability: "{{ item }}"
    state: present
  with_items:
    - "cap_net_raw+eip"
    - "cap_net_admin+eip"

- name: Set broctl cron
  cron:
    name: "broctl maintenance"
    minute: "*/5"
    cron_file: rocknsm_broctl
    user: "{{ bro_user }}"
    job: "/opt/bro/bin/broctl cron >/dev/null 2>&1"

- name: Initialize bro scripts for workers
  command: /opt/bro/bin/broctl install
  args:
    creates: "{{ bro_data_dir }}/spool/broctl-config.sh"
  become: yes
  become_user: "{{ bro_user }}"
 
-  name: Enable and start broctl
   service:
     name: broctl
     enabled: "{{ enable_bro }}"
     state: "{{ 'started' if enable_bro else 'stopped' }}"
