#######################################################
###################  Docker Install ###################
#######################################################
---

- name: "Setup Docker repo"
  when: rock_online_install and containerized_install
  yum_repository: 
    baseurl: "{{ docker_baseurl }}"
    description: "Docker YUM repo"
    gpgcheck: true
    gpgkey: "{{ docker_gpgurl }}"
    name: docker-ce

# create directories to move Docker images into central storage location
- file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '/etc/systemd/system/docker.service.d'

# create file to overrun Docker startup to change default image location
- file:
    path: '/etc/systemd/system/docker.service.d/docker.root.conf'
    state: touch

- name: 'Set Docker service file'
  shell: echo "[Service]" > /etc/systemd/system/docker.service.d/docker.root.conf; echo "ExecStart=" >> /etc/systemd/system/docker.service.d/docker.root.conf; echo "ExecStart=/usr/bin/dockerd -g {{ rocknsm_dir }}/docker" >> /etc/systemd/system/docker.service.d/docker.root.conf
  notify: reload systemd

- name: 'Install Docker package'
  yum:
    name: 'docker-ce'
    state: 'installed'

# Set Docker Virtual Memory
- sysctl: 
    name: 'vm.max_map_count'
    value: '262144'
    sysctl_file: '/etc/sysctl.conf'
    state: present
    sysctl_set: yes
  notify: reload systemd

- name: 'Install python-docker-py'
  yum: 
    name: 'python-docker-py.noarch'
    state: 'installed'

- name: 'Install docker_compose'
  yum:
    name: 'docker-compose' 
    state: 'installed'

- name: 'Start Docker'
  service:
    name: 'docker'
    state: 'started'

- name: 'Enable Docker service'
  service:
    name: 'docker'
    enabled: yes
