---
# TFPlenum
version: 3.0
online_install: true
debug_enabled: true
install_user: root
install_group: root
install_dir: /opt/dmss
sysctl_file: /etc/sysctl.d/dmss.conf
fqdn: default.svc.cluster.local

# Redis
redis_sentinel_port: 26379

# Elasticsearch
elastic_ver: '6.2.2'
es_cluster_name: dmss
elastic_fqdn: "elasticsearch.{{ fqdn }}"
elastic_port: 9200

# If you have licensing for x-pack set variable to true.
xpack_license: 'true'

# Kubernetes
kubernetes_conf_file: /etc/kubernetes/admin.conf
kube_dir: "{{ install_dir }}/kubernetes"
kube_version: "1.9.3"

# Bro
pulled_pork_oinkcode: 796f26a2188c4c953ced38ff3ec899d8ae543350
bro_rockscripts_repo: https://github.com/rocknsm/rock-scripts.git
pulled_pork_repo: https://github.com/shirkdog/pulledpork.git

# Kafka
kafka_fqdn: "kafka.{{ fqdn }}"
kafka_port: 9092
kafka_retention: 168

# Common
package_list:
#  - java-1.8.0-openjdk-headless
#  - jq
#  - GeoIP
#  - GeoIP-update
#  - tcpreplay
#  - tcpdump
#  - bats
#  - policycoreutils-python
#  - htop
#  - vim
#  - git
#  - tmux
#  - nmap-ncat
#  - logrotate
#  - perl-LWP-Protocol-https
#  - perl-Sys-Syslog
#  - perl-Crypt-SSLeay
#  - perl-Archive-Tar
#  - easy-rsa
  - chrony
  - postfix
  - cockpit
  - cockpit-dashboard
  - cockpit-machines
  - cockpit-networkmanager
  - cockpit-packagekit
  - cockpit-storaged
  - cockpit-system
  - python-gobject
  - NetworkManager-glib

# RockNSM
#rocknsm_baseurl: https://packagecloud.io/rocknsm/2/el/7/$basearch
#rocknsm_gpgurl: https://packagecloud.io/rocknsm/2/gpgkey
rocknsm_baseurl: 'https://copr-be.cloud.fedoraproject.org/results/@rocknsm/rocknsm-2.1/epel-7-$basearch/'
rocknsm_gpgurl: 'https://copr-be.cloud.fedoraproject.org/results/@rocknsm/rocknsm-2.1/pubkey.gpg'
...
