---
# TFPlenum
version: 3.0
online_install: true
debug_enabled: true
install_user: root
install_group: root
install_dir: /opt/rock
sysctl_file: /etc/sysctl.d/rock.conf
fqdn: default.svc.cluster.local

# Redis
redis_sentinel_port: 26379

# Elasticsearch
elastic_ver: '6.2.4'
elastic_cluster_name: rock
elastic_fqdn: "elasticsearch.{{ fqdn }}"
elastic_port: 9200

# Kibana
kibana_fqdn: "kibana.{{ fqdn }}"

# If you have licensing for x-pack set variable to true.
xpack_license: 'true'

# Kubernetes
kubernetelastic_conf_file: /etc/kubernetes/admin.conf
kube_dir: "{{ install_dir }}/kubernetes"
kube_version: "1.9.7"

# Bro
pulled_pork_oinkcode: 796f26a2188c4c953ced38ff3ec899d8ae543350
bro_rockscripts_repo: https://github.com/rocknsm/rock-scripts.git
pulled_pork_repo: https://github.com/shirkdog/pulledpork.git

# Kafka
kafka_fqdn: "kafka.{{ fqdn }}"
kafka_port: 9092
kafka_retention: 168

# Common
package_list:
  - cockpit
  - cockpit-dashboard
  - cockpit-machines
  - cockpit-networkmanager
  - cockpit-packagekit
  #- cockpit-storaged - this is currently broken TODO: we need to look into this. See: https://github.com/tfplenum/rock/issues/323
  - cockpit-system
  - python-gobject
  - python-docker-py.noarch
  - nload

# RockNSM
#rocknsm_baseurl: https://packagecloud.io/rocknsm/2/el/7/$basearch
#rocknsm_gpgurl: https://packagecloud.io/rocknsm/2/gpgkey
rocknsm_baseurl: 'https://copr-be.cloud.fedoraproject.org/results/@rocknsm/rocknsm-2.1/epel-7-$basearch/'
rocknsm_gpgurl: 'https://copr-be.cloud.fedoraproject.org/results/@rocknsm/rocknsm-2.1/pubkey.gpg'
...
