# Uninstall GlusterFS
---

- name: Gluster | Scale down deploy-heketi gracefully
  shell: "kubectl scale deployment deploy-heketi --replicas=0"
  when: inventory_hostname in groups['master-server']
  ignore_errors: yes

- name: Gluster | Scale down heketi gracefully
  shell: "kubectl scale deployment heketi --replicas=0"
  when: inventory_hostname in groups['master-server']
  ignore_errors: yes

- name: Gluster | Wait for Scale Down
  pause:
    seconds: 35

- name: Gluster | Wait for Pods To Terminate
  shell: |
    {% raw %}
    GOPOD='{{range .items}}{{range .status.containerStatuses}}{{if .state.terminated}}terminated{{end}}{{end}}{{end}}'
    kubectl get pods --selector=glusterfs -o go-template --template="$GOPOD"
    {% endraw %} 
  register: output
  until: output.stdout == ""
  retries: 30
  delay: 15
  when: inventory_hostname in groups['master-server'] 

- name: Flush Deploy Heketi
  shell: |
    kubectl delete all,svc,jobs,deploy,secret --selector="deploy-heketi"
  ignore_errors: yes

- name: Flush Heketi
  shell: |
    kubectl delete all,svc,deploy,secret,sa,clusterrolebinding --selector="heketi"
  ignore_errors: yes

- name: Flush Heketi
  shell: |
    kubectl delete svc heketi-storage-endpoints
  ignore_errors: yes

- name: Remove Node Label
  shell: "kubectl label nodes {{ item }} storagenode-"
  when: inventory_hostname in groups['master-server']
  with_items:
  - "{{ groups['master-server'] }}"
  - "{{ groups['nodes'] }}"
  ignore_errors: yes

- name: Flush Heketi
  shell: |
    kubectl  delete ds --selector="glusterfs"
  ignore_errors: yes

- name: Uninstall GlusterFS client
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - glusterfs-client
    - heketi-client
  ignore_errors: yes

- name: Remove Centos repo
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - "centos-release-gluster{{ centos_gluster_ver }}"
  #when: ansible_distribution == 'CentOS'
  ignore_errors: yes

- name: "Remove RedHat repo"
  yum_repository:
    baseurl: "http://mirror.centos.org/centos/7/storage/x86_64/gluster-{{ gluster_ver }}/"
    description: "Gluster repository"
    gpgcheck: no
    name: CentOS-Gluster-3.10
    state: absent
  when: ansible_distribution == 'RedHat'
  ignore_errors: yes

- name: Remove possible artifacts
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/lib/heketi
    - /var/lib/glusterfs
    - /var/lib/glusterd
    - /etc/glusterfs
  ignore_errors: yes

- name: Remove Gluster Directory
  file:
    path: "{{ gluster_dir }}"
    state: absent
    owner: root
    group: root
    mode: 0644
  when: inventory_hostname in groups['master-server']
  ignore_errors: yes