---
- name: ABOUT TO DESTROY DATA ON ALL DEVICES PROVIDED FOR STORAGE IN INVENTORY FILE
  pause:
    seconds: 10

# TODO - this needs a guard - what if someone forgets to define the data disk
# or they put in the wrong thing
- name: WIPEING DATA
  shell: "dmsetup remove_all; wipefs -af {{ item }}"
  with_items:
    - "{{ ceph_disks }}"