---
# handlers file for rocknsm.docket
- name: docket | cleanup csr on docket host
  file:
    path: "{{docket_x509_key}}.csr"
    state: absent
  when: inventory_hostname in groups['docket']

- name: docket | cleanup csr on sensor hosts
  file:
    path: "{{steno_certs_dir}}/{{hostvars[item].inventory_hostname}}.csr"
    state: absent
  with_items: groups['docket']
  when:
    - inventory_hostname in groups['stenographer']

- name: docket | restart redis
  service:
    name: redis
    state: restarted

- name: docket | seed random key
  lineinfile:
    path: /etc/docket/prod.yml
    regexp: 'XX_NOT_A_SECRET_XX'
    line: "SECRET_KEY: {{ docket_secret }}"
    state: present

- name: docket | restart docket celery services
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - docket-celery-io
    - docket-celery-query

- name: docket | restart docket uwsgi
  service:
    name: docket
    state: restarted

- name: docket | restart lighttpd
  service:
    name: lighttpd
    state: restarted
