######################################################
################### Setup Logstash ###################
######################################################
--- 
- 
  name: "Install Bro-Kafka configuration for Logstash"
  copy: 
    dest: /etc/logstash/conf.d/kafka-bro.conf
    group: "{{ logstash_group }}"
    mode: 416
    owner: "{{ logstash_user }}"
    src: logstash-kafka-bro.conf
  notify: "Restart Logstash"
  when: "with_logstash and with_bro and with_kafka"
- 
  name: "Install Suricata-Kafka configuration for Logstash"
  copy: 
    dest: /etc/logstash/conf.d/kafka-suricata.conf
    group: "{{ logstash_group }}"
    mode: 416
    owner: "{{ logstash_user }}"
    src: logstash-kafka-suricata.conf
  notify: "Restart Logstash"
  when: "with_logstash and with_suricata and with_kafka"
- 
  name: "Install FSF-Kafka configuration for Logstash"
  copy: 
    dest: /etc/logstash/conf.d/kafka-fsf.conf
    group: "{{ logstash_group }}"
    mode: 416
    owner: "{{ logstash_user }}"
    src: logstash-kafka-fsf.conf
  notify: "Restart Logstash"
  when: "with_logstash and with_fsf and with_kafka"
- 
  name: "Enable and start Logstash"
  service: 
    enabled: "{{ enable_logstash }}"
    name: logstash
    state: "{{ 'started' if enable_logstash else 'stopped' }}"
  when: with_logstash
