#######################################################
###################  Kubernetes Setup Nodes ###############
#######################################################
---

- import_tasks: 00_preflight.yml

- name: Install New Node
  block:
    - import_tasks: 05_install.yml
    - import_tasks: 10_remote_sensor.yml
\
- name: Label master node with appropriate roles
  import_role:
    name: kubernetes/common
    tasks_from: label_nodes.yml

...
