######################################################
############### Setup Moloch container ###############
######################################################
---

- name: 'Create directories'
  file:
    path: "{{ moloch_dir }}"
    owner: "{{ moloch_user }}"
    group: "{{ moloch_group }}"
    mode: "{{ moloch_dir_mode }}"
    state: directory

- name: 'Copy files'
  copy:
    src: files/{{ item }}
    dest: "{{ moloch_dir }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - config.ini.tmpl
    - config.ini.conf

- name: 'Copy config files'
  template:
    src: "templates/{{ item }}"
    dest: "{{ moloch_dir }}/{{ item }}"
    mode: "{{ moloch_file_mode }}"
    owner: "{{ moloch_user }}"
    group: "{{ moloch_group }}"
  with_items:
    - auto_init
    - bootstrap.yml
    - deploy.yml
    - svc.yml

- name: "Clean up kube configmap"
  command: "kubectl delete configmap {{ item }} --ignore-not-found"
  with_items:
    - moloch
    - moloch-bootstrap

- name: "Clean up kube for deployment "
  command: "kubectl delete -f {{ moloch_dir }}/{{ item }}.yml --ignore-not-found"
  with_items:
    - bootstrap
    - deploy
    - svc

- name: "Wait for deployment to cleanup"
  shell: |
    while [ $(kubectl get pods | grep moloch | wc -l) -gt 0 ]; do
      echo -n .;
      sleep 1;
    done;

- name: "Create kube config"
  shell: |
    kubectl create configmap moloch --from-file {{ moloch_dir }}/config.ini.tmpl \
      --from-file {{ moloch_dir }}/config.ini.conf

- name: "Create kube bootstrap config"
  shell: "kubectl create configmap moloch-bootstrap --from-file {{ moloch_dir }}/auto_init"

- name: Deploy Bootstrap
  command: "kubectl create -f {{ moloch_dir }}/bootstrap.yml"

- name: Get Bootstrap pod name
  shell: |
    while [ "$(kubectl get pods | grep moloch-bootstrap | head -n 1 | awk '{ print $2}')" != "1/1" ]; do
      sleep 1;
    done;
    echo -n "$(kubectl get pods | grep moloch-bootstrap | head -n 1 | awk '{ print $1 }')"
  register: moloch_bootstrap_pod

- name: Stop moloch services
  shell: "kubectl exec -ti {{ moloch_bootstrap_pod.stdout }} -- /bin/bash -c 'systemctl stop molochcapture molochviewer'"
  ignore_errors: yes

- name: Configure Elasticsearch for moloch
  shell: "kubectl exec {{ moloch_bootstrap_pod.stdout }} -- /usr/bin/expect /tmp/auto_init"
  register: debug_output
  ignore_errors: yes

- name: Debut Outout
  debug: "msg={{ debug_output.stdout }}"

- name: Add user
  command: "kubectl exec -ti {{ moloch_bootstrap_pod.stdout }} -- {{ moloch_path }}/bin/moloch_add_user.sh -c {{ moloch_path }}/etc/config.ini {{ moloch_login }} {{ moloch_login }} {{ moloch_pass }} --admin --webauth"

- name: Remove Bootstrap
  command: kubectl delete -f {{ moloch_dir }}/bootstrap.yml --ignore-not-found

- name: Remove Bootstrap config
  command: kubectl delete configmap moloch-bootstrap

- name: "Deploy moloch"
  command: "kubectl create -f {{ moloch_dir }}/{{ item }}.yml"
  with_items:
    - deploy
    - svc

...
