#
# Checking that required variables are set
#
- name: Checking that required variables are set
  fail:
    msg: "kube_dir is not defined. It must be defined for Kubernetes to continue."
  when: kube_dir is not defined or kube_dir is none

- name: Checking that required variables are set
  fail:
    msg: "kube_pod_cidr is not defined. It must be defined for Kubernetes to continue."
  when: kube_pod_cidr is not defined or kube_pod_cidr is none

- name: Checking that required variables are set
  fail:
    msg: "kube_rpm_version is not defined. It must be defined for Kubernetes to continue."
  when: kube_rpm_version is not defined or kube_rpm_version is none

- name: Checking that required variables are set
  fail:
    msg: "kubernetes_conf_file is not defined. It must be defined for Kubernetes to continue."
  when: kubernetes_conf_file is not defined or kubernetes_conf_file is none

- name: Checking that required variables are set
  fail:
    msg: "kafka_fqdn is not defined. It must be defined for Kubernetes to continue."
  when: kafka_fqdn is not defined or kafka_fqdn is none

- name: Checking that required variables are set
  fail:
    msg: "kafka_port is not defined. It must be defined for Kubernetes to continue."
  when: kafka_port is not defined or kafka_port is none

- name: Checking that required variables are set
  fail:
    msg: "elastic_fqdn is not defined. It must be defined for Kubernetes to continue."
  when: elastic_fqdn is not defined or elastic_fqdn is none

- name: Checking that required variables are set
  fail:
    msg: "elastic_port is not defined. It must be defined for Kubernetes to continue."
  when: elastic_port is not defined or elastic_port is none

- name: Check Master Node
  import_role:
    name: kubernetes/common
    tasks_from: kube_check
  vars:
    type: "node"
    namespace: ""
    resource_name: "{{ ansible_fqdn }}"
    label: ""
