---

- name: Copy Config File
  copy:
    src: "metallb.yaml"
    dest: "{{ kube_dir }}/metallb.yaml"
    owner: root
    group: root
    mode: 0644

- name: 'Install MetalLB LoadBalancer'
  command: 'kubectl apply -f {{ kube_dir }}/metallb.yaml'

- name: 'Apply MetalLB Config'
  command: 'kubectl apply -f {{ kube_dir }}/metallb.yml'

- name: Wait for metallb to be ready
  include_role:
    name: kubernetes/common
    tasks_from: kube_wait
  vars:
    type: "pods"
    namespace: "metallb-system"
    resource_name: ""
    label: ""
