%YAML 1.1
---

#### Retention Configuration ####

# TODO: We will need to clean this up

#elastic_close_interval: 15
#elastic_delete_interval: 60


#### Main Role Configuration ####

es_user: 1000
es_group: 1000
#elastic_data_port: '9200'
#elastic_management_port: '9300'
elastic_image: 'grantcurell/elasticsearch'
elastic_dir: "{{ install_dir  }}/elasticsearch"
#elastic_pv_data_path: "/usr/share/elasticsearch/data"
#elastic_config_path: "/usr/share/elasticsearch/config"
#elastic_pv_size: 1
elasticsearch_memory: 2
#es_masters: 3
#es_datas: 0

num_replicas: 3
