---

- name: Install packages
  yum:
    name: stenographer

# tasks file for stenographer
  ######################################################
  ################# Config Stenographer #################
  ######################################################
- name: Set stenographer config
  template:
    src: templates/stenographer-config.j2
    dest: "/etc/stenographer/config.{{ item.1 }}"
  with_indexed_items: "{{ stenographer_monitor_interface }}"

- name: Create Stenographer directories
  file:
    path: "{{ stenographer_data_dir }}/{{ item[0] }}/{{ item[1] }}"
    mode: 0755
    owner: "{{ stenographer_user }}"
    group: "{{ stenographer_group }}"
    state: directory
  with_nested:
    - "{{ stenographer_monitor_interface }}"
    - [ 'index', 'packets' ]

- name: Install stenographer service files
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    mode: 0644
    owner: root
    group: root
  with_items:
    - stenographer.service
    - stenographer@.service

- name: Generate stenographer keys
  command: >
    /usr/bin/stenokeys.sh {{ stenographer_user }} {{ stenographer_group }}
  args:
    creates: /etc/stenographer/certs/client_key.pem

- name: Configure Stenographer service
  systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    name: stenographer

- name: configure stenographer per interface
  systemd:
    name: "stenographer@{{ item }}"
    enabled: yes
    daemon_reload: yes
  with_items: "{{ stenographer_monitor_interface }}"

...
