---
- name: Configure firewalld
  firewalld:
    port: "{{ item[1].port }}"
    source: "{{ item[0] }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_nested:
    - "{{ rock_mgmt_nets }}"
    -
      - { port: "443/tcp" }
...
