---
######################################################
############## Setup Lighttpd container ##############
######################################################

# Depending on the OS there may already be a httpd running
- name: 'Check if pre-existing httpd service exists'
  stat: 'path=/etc/init.d/httpd'
  register: 'service_status'

- name: 'Disable local http server'
  service:
    name: 'httpd'
    enabled: no
    state: 'stopped'
  when: 'service_status.stat.exists'

- name: 'Create new directories'
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - "{{ rocknsm_dir }}/lighttpd/var/www"
    - "{{ rocknsm_dir }}/lighttpd/var/log"
    - "{{ rocknsm_dir }}/lighttpd/etc/lighttpd/conf.d"

- name: 'Copy lighttpd dockerfile'
  template:
    src: 'lighttpd-dockerfile.j2'
    dest: "{{ rocknsm_dir }}/lighttpd/lighttpd-dockerfile"
    mode: 0644
    owner: root
    group: root

- name: 'Build lighttpd container'
  docker_image:
    name: 'rocknsm/lighttpd'
    pull: yes
    state: present
    path: "{{ rocknsm_dir }}/lighttpd/"
    dockerfile: 'lighttpd-dockerfile'
  when: rock_online_install

- name: 'Install Lighttpd service file'
  template:
    src: 'lighttpd.service.j2'
    dest: '/etc/systemd/system/lighttpd.service'
    mode: 0644
    owner: root
    group: root
  notify: reload systemd

- name: 'Copy Lighttpd compose file'
  template:
    src: 'lighttpd-compose.yml.j2'
    dest: "{{ rocknsm_dir }}/lighttpd/lighttpd-compose.yml"
    mode: 0644
    owner: root
    group: root

- name: 'Copy proxy.conf file'
  template:
    src: 'proxy.conf.j2'
    dest: "{{ rocknsm_dir }}/lighttpd/etc/lighttpd/conf.d/proxy.conf"
    mode: 0644
    owner: root
    group: root

- name: 'Copy lighttpd.conf file'
  template:
    src: 'lighttpd.conf.j2'
    dest: "{{ rocknsm_dir }}/lighttpd/etc/lighttpd/lighttpd.conf"
    mode: 0644
    owner: root
    group: root

- name: 'Copy modules.conf file'
  template:
    src: 'modules.conf.j2'
    dest: "{{ rocknsm_dir }}/lighttpd/etc/lighttpd/modules.conf"
    mode: 0644
    owner: root
    group: root

- name: 'Run lighttpd-compose.yml'
  docker_service:
    project_src: "{{ rocknsm_dir }}/lighttpd/"
    files: 'lighttpd-compose.yml'
    state: present

- name: 'Enable Lighttpd service'
  service:
    name: 'lighttpd'
    enabled: yes

- name: 'Copy web content into Lighttpd'
  copy:
    src: Rocknsm
    dest: "{{ rocknsm_dir }}/lighttpd/var/www/"
    directory_mode: true

...
