---

############################################
# Checking that required variables are set #
############################################

- name: Check if remote-sensors is defined
  fail:
    msg: 'Verify you have the remote-sensors group in your inventory file. It must be defined. See sample inventory. If you have no remote sensors you can define an empty group with just remote-senors: under nodes.'
  when: "'remote-sensors' not in groups"

- name: Checking that management_ipv4 is set
  fail:
    msg: "management_ipv4 is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: management_ipv4 is not defined or management_ipv4 is none

- name: Checking that home_net is set
  fail:
    msg: "home_net is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: home_net is not defined or home_net is none

- name: Checking that services_cidr is set
  fail:
    msg: "services_cidr is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: services_cidr is not defined or services_cidr is none

- name: Checking that bpf_filter is set
  fail:
    msg: "bpf_filter is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: bpf_filter is not defined or bpf_filter is none

- name: Checking that es_mem is set
  fail:
    msg: "es_mem is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: es_mem is not defined or es_mem is none

- name: Checking that es_masters is set
  fail:
    msg: "es_masters is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: es_masters is not defined or es_masters is none

- name: Checking that pcap_bpf_filter is set
  fail:
    msg: "pcap_bpf_filter is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: pcap_bpf_filter is not defined or pcap_bpf_filter is none

- name: Checking that es_datas is set
  fail:
    msg: "es_datas is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: es_datas is not defined or es_datas is none

- name: Checking that elastic_pv_size
  fail:
    msg: "elastic_pv_size is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: elastic_pv_size is not defined or elastic_pv_size is none

- name: Checking that kafka_pv_size is set
  fail:
    msg: "kafka_pv_size is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: kafka_pv_size is not defined or kafka_pv_size is none

- name: Checking that zookeeper_pv_size is set
  fail:
    msg: "zookeeper_pv_size is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: zookeeper_pv_size is not defined or zookeeper_pv_size is none

- name: Checking that zookeeper_replicas is set
  fail:
    msg: "zookeeper_replicas is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: zookeeper_replicas is not defined or zookeeper_replicas is none

- name: Checking that pcap_pv_size is set
  fail:
    msg: "pcap_pv_size is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: pcap_pv_size is not defined or pcap_pv_size is none

- name: Checking that dns_ip is set
  fail:
    msg: "dns_ip is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: dns_ip is not defined or dns_ip is none

- name: Checking that zookeeper_mem is set
  fail:
    msg: "zookeeper_mem is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: zookeeper_mem is not defined or zookeeper_mem is none

- name: Checking that kakfa_mem is set
  fail:
    msg: "kafka_mem is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: kafka_mem is not defined or kafka_mem is none

- name: Checking that monitor_interfaces is set
  fail:
    msg: "monitor_interfaces is not defined. Make sure it is defined in your inventory file. See sample inventory for help. All sensors must have monitor interface defined."
  when: inventory_hostname in groups['sensors'] and (monitor_interfaces is not defined or monitor_interfaces is none)

- name: Checking that bro_wokers is set
  fail:
    msg: "bro_workers is not defined. Make sure it is defined in your inventory file. See sample inventory for help. This host is in the bro group and subsequently must have a bro workers count. Keep in mind bro_workers must be non-zero. If you want to get rid of bro, take the host out of the bro group."
  when: inventory_hostname in groups['bro'] and (bro_workers is not defined or bro_wokers is none or (bro_workers | int) == 0)

- name: Checking that moloch_spiDataMaxIndices is set
  fail:
    msg: "moloch_spiDataMaxIndices is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: moloch_spiDataMaxIndices is not defined or moloch_spiDataMaxIndices is none

- name: Checking that moloch_pcapWriteMethod is set
  fail:
    msg: "moloch_pcapWriteMethod is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: moloch_pcapWriteMethod is not defined or moloch_pcapWriteMethod is none

- name: Checking that moloch_pcapWriteSize is set
  fail:
    msg: "moloch_pcapWriteSize is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: moloch_pcapWriteSize is not defined or moloch_pcapWriteSize is none

- name: Checking that moloch_pcapWriteMethod is set
  fail:
    msg: "moloch_pcapWriteMethod is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: moloch_pcapWriteMethod is not defined or moloch_pcapWriteMethod is none

- name: Checking that moloch_maxESConns is set
  fail:
    msg: "moloch_maxESConns is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: moloch_maxESConns is not defined or moloch_maxESConns is none

- name: Checking that moloch_maxESRequests is set
  fail:
    msg: "moloch_maxESRequests is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: moloch_maxESRequests is not defined or moloch_maxESRequests is none

- name: Checking that moloch_packetsPerPoll is set
  fail:
    msg: "moloch_packetsPerPoll is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: moloch_packetsPerPoll is not defined or moloch_packetsPerPoll is none

- name: Checking that moloch_magicMode is set
  fail:
    msg: "moloch_magicMode is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: moloch_magicMode is not defined or moloch_magicMode is none

- name: Checking that moloch_maxPacketsInQueue is set
  fail:
    msg: "moloch_maxPacketsInQueue is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: moloch_maxPacketsInQueue is not defined or moloch_maxPacketsInQueue is none

- name: Checking that pcap_cluster is set
  fail:
    msg: "pcap_cluster is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: pcap_cluster is not defined or pcap_cluster is none

- name: Checking that moloch_threads is set
  fail:
    msg: "moloch_threads is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: inventory_hostname in groups['sensors'] and moloch_threads is not defined or moloch_threads is none

...
