---

- name: Verify PCAP directory exists
  stat:
    path: "{{ moloch_pcap_folder }}"
  register: moloch_pcap_folder_test
  when: not use_ceph_for_pcap and pcap_disk is none

- name: Verify PCAP directory exists
  fail:
    msg: "You set use_ceph_for_pcap to false indicating you plan to use direct attached storage for PCAP. The PCAP directory you defined {{ moloch_pcap_folder }} does not exist or is not a directory. Verify it both exists and is a directory."
  when: not use_ceph_for_pcap and pcap_disk is none and (not moloch_pcap_folder_test.stat.exists or not moloch_pcap_folder_test.stat.isdir)

...
