---
######################################################
################# Setup Kibana #######################
######################################################

- name: "Create config directory"
  file:
    path: "{{ kibana_dir }}"
    state: directory
    owner: root
    group: root
    mode: u+rw,g+rw

- name: Install templates
  template:
    src: "templates/{{ item }}.yml.j2"
    dest: "{{ kibana_dir }}/{{ item }}.yml"
    group: root
    owner: root
    mode: 0644
  with_items:
    - deploy
    - svc

- name: Flush Deployments
  shell: |
    kubectl --kubeconfig {{ kubernetes_conf_file }} delete -f {{ kibana_dir }}/{{ item }}.yml
    while [ $(kubectl --kubeconfig {{ kubernetes_conf_file }} get -f {{ kibana_dir }}/{{ item }}.yml | tail -n +2 | wc -l) != '0' ]; do
      echo -n .;
      sleep 1;
    done;
  with_items:
    - deploy
    - svc
  ignore_errors: true

- name: Kibana | Deploy Deployment
  shell: "kubectl --kubeconfig {{ kubernetes_conf_file }} create -f {{ kibana_dir }}/deploy.yml"

- name: Wait for kibana to be ready
  include_role:
    name: kubernetes/common
    tasks_from: kube_wait
  vars:
    type: "deployments"
    namespace: "default"
    resource_name: "kibana"
    label: ""

- name: Kibana | Deploy Service
  shell: "kubectl --kubeconfig {{ kubernetes_conf_file }} create -f {{ kibana_dir }}/svc.yml"
