#######################################################
###################  Harbor Install ###################
#######################################################
---

- name: "Download Harbor {{ harbor_ver }} build"
  unarchive:
    src: "https://github.com/vmware/harbor/releases/download/v{{ harbor_ver }}/harbor-online-installer-v{{ harbor_ver }}.tgz"
    dest: "{{ rocknsm_dir }}"
    mode: 0740
    remote_src: true

- name: 'Fix Harbor config'
  block:
    - name: 'Set up harbor.cfg'
      replace:
        path: "{{ rocknsm_dir }}/harbor/harbor.cfg"
        regexp: '(\s+)hostname = reg\.mydomain\.com(\s+.*)?$'
        replace: '\1hostname = {{ rock_hostname }}\2'
    - replace:
        path: "{{ rocknsm_dir }}/harbor/harbor.cfg"
        regexp: '(\s+)db_password = root123(\s+.*)?$'
        replace: '\1db_password = password\2'
    - replace: 
        path: "{{ rocknsm_dir }}/harbor/harbor.cfg"
        regexp: '(\s+)harbor_admin_password = Harbor12345(\s+.*)?$'
        replace: '\1harbor_admin_password = password\2'

- name: 'Fix Harbor docker-compose file'
  replace:
    path: "{{ rocknsm_dir }}/harbor/docker-compose.yml"
    regexp: '(\s+)80:80\(\s+.*)?$'
    replace: '\1{{ harbor_firewall_port }}:{{ harbor_port }}\2'

# Depending on the OS there may already be a httpd running
- name: 'Check if pre-existing httpd service exists'
  stat: 'path=/etc/init.d/httpd'
  register: 'service_status'

- name: 'Disable local http server'
  service:
    name: 'httpd'
    enabled: no
    state: 'stopped'
  when: 'service_status.stat.exists'

- name: 'Install Harbor'
  shell: "sh {{ rocknsm_dir }}/harbor/install.sh" 

- name: 'Install Harbor service file'
  template:
    backup: yes
    src: 'harbor.service.j2'
    dest: '/etc/systemd/system/harbor.service'
    owner: root
    group: root
    mode: 0644

- name: 'Enable harbor service'
  service: 
    name: 'harbor'
    enabled: yes

- name: 'Copy images script'
  copy:
    src: 'import_harbor_images.sh'
    dest: "{{ rocknsm_dir }}/harbor/import_harbor_images.sh"
    mode: 0550
    owner: root
    group: root

- name: 'Import existing Docker images into Harbor'
  shell: "sh {{ rocknsm_dir }}/harbor/import_harbor_images.sh"

- name: 'Zeroing import script passwords'
  replace: 
    path: "{{ rocknsm_dir }}/harbor/import_harbor_images.sh"
    regexp: '(\s+)docker login --username="admin" --password="password"(\s+.*)?$'
    replace: '\1docker login\2'

...

