######################################################
############### Setup Kafka container ###############
######################################################

---

- name: 'Add RockNSM Yum Corp Repo File'
  yum_repository:
    name: rocknsm_corp
    description: rocknsm corp repo
    baseurl: https://copr-be.cloud.fedoraproject.org/results/@rocknsm/rocknsm-2.1/epel-7-$basearch/
    gpgcheck: false

- name: 'Create Kafka data directory'
  file:
    path: "{{ kafka_data_dir }}"
    state: directory
    mode: 0744

- name: 'Create Kafka directory'
  file:
    path: "{{ kafka_dir }}"
    state: directory
    mode: 0644

# Install Kafkacat for the dockervm
# TODO: Is this needed?
#- name: Install Kafkacat package
#  yum:
#    name: kafkacat
#    state: installed

- name: 'Install Kafka service file'
  template:
    src: 'kafka.service.j2'
    dest: '/etc/systemd/system/kafka.service'
    mode: 0644
    owner: root
    group: root

- name: 'Copy Kafka dockerfile'
  template:
    src: 'kafka-dockerfile.j2'
    dest: "{{ kafka_dir }}/kafka-dockerfile.j2"
    mode: 0644
    owner: root
    group: root

- name: 'Copy Kafka start_kafka script'
  copy:
    src: 'start-kafka.sh'
    dest: "{{ kafka_dir }}/start-kafka.sh"
    mode: 0644
    owner: root
    group: root

- name: 'Build Kafka container'
  docker_image:
    name: 'rocknsm/kafka'
    pull: yes
    state: present
    path: "{{ kafka_dir }}/"
    dockerfile: 'kafka-dockerfile.j2'
  when: rock_online_install

- name: 'Copy Kafka server.properties file'
  copy:
    src: 'server.properties'
    dest: "{{ kafka_dir }}/server.properties"
    mode: 0644
    owner: root
    group: root

- name: 'Copy Kafka compose file'
  template:
    src: 'kafka-compose.yml.j2'
    dest: "{{ rock_compose_files }}/kafka-compose.yml.j2"
    mode: 0644
    owner: root
    group: root

- name: 'Enable Kafka service'
  systemd:
    name: 'kafka'
    enabled: yes
    state: started
    daemon-reload: yes

- name: 'Wait for Kafka service to start'
  pause:
    seconds: 20

# TODO: Need to add a dependency on zookeeper
- name: create kafka bro topic
  command: >
    docker exec {{ kafka_container_name }} /opt/kafka/bin/kafka-topics.sh
       --zookeeper {{ zookeeper_container_name }}:2181
       --create
       --replication-factor 1
       --topic bro-raw
       --partitions 1
  ignore_errors: yes

- name: create kafka suricata topic
  command: >
    docker exec {{ kafka_container_name }} /opt/kafka/bin/kafka-topics.sh
       --zookeeper {{ zookeeper_container_name }}:2181
       --create
       --replication-factor 1
       --topic suricata-raw
       --partitions 1
  ignore_errors: yes

- name: create kafka fsf topic
  command: >
    docker exec {{ kafka_container_name }} /opt/kafka/bin/kafka-topics.sh
       --zookeeper {{ zookeeper_container_name }}:2181
       --create
       --replication-factor 1
       --topic fsf-raw
       --partitions 1
  ignore_errors: yes
