---
# defaults file for stenographer
stenographer_packagename: stenographer
stenographer_user: stenographer
stenographer_group: stenographer
stenographer_monitor_interfaces: [eth0]
enable_stenographer: true
method: deploy
