##############################################
# ----- Example Logstash Configuration ----- #
##############################################

# file paths; data and logs path must be writeable by the logstash user
path.data: /var/lib/logstash
path.config: /etc/logstash/conf.d
path.logs: /var/log/logstash

# Automatic reload of config files
# You don't have to restart the logstash service after making changes

# config.reload.automatic: true
# config.reload.interval: 10

# queue types are 'memory' and 'persisted'
# persisted writes the logs to disk before processing them.
# This can help prevent Logstash from getting overwhelmed
# during temporary spikes in event rates
# queue.max_bytes is the size of the queue and is only used with persisted

queue.type: persisted
queue.max_bytes: 2gb

# x-pack features are optional and require a license
# monitoring is included in the free license.
# monitoring allows you to monitor the performance of logstash
# Things monitored: event rates, event latency, JVM Heap, System Load.

xpack.monitoring.enabled: false
