######################################################
################### Setup Filebeat ###################
######################################################

---

- name: 'Download Filebeat container'
  docker_image:
    name: "{{ filebeat_image }}:{{ filebeat_ver }}"

- name: 'Create filebeat directory'
  file:
    path: "{{ filebeat_config_location }}"
    state: directory
    mode: 0754

- name: "Add Filebeat configuration file"
  template:
    dest: "{{ filebeat_config_location }}/filebeat.yml"
    src: filebeat.yml.j2

- name: 'Install Filebeat service file'
  template:
    src: 'filebeat.service.j2'
    dest: '/etc/systemd/system/filebeat.service'
    mode: 0644
    owner: root
    group: root

- name: 'Copy Filebeat compose file'
  template:
    src: 'filebeat-compose.yml.j2'
    dest: "{{ rock_compose_files }}/filebeat-compose.yml.j2"
    mode: 0644
    owner: root
    group: root

- name: 'Enable Filebeat service'
  systemd:
    name: 'filebeat'
    enabled: yes
    state: restarted
    daemon_reload: yes

...
