---
- set_fact:
    module: "br_netfilter"

- name: Enable modules 
  modprobe:
    name: "{{ module }}"
    state: present
  #with_items:
  #  - "{{ modlist }}"

- file:
    path: /etc/modules-load.d/99-k8.conf
    state: touch
    owner: root
    group: root
    mode: 0644

- lineinfile:
    path: /etc/modules-load.d/99-k8.conf
    line: '{{ module }}'