# Install GlusterFS
---
- name: Gluster | Create Cluster Role Binding
  shell: "kubectl create clusterrolebinding heketi-gluster-admin --clusterrole=edit --serviceaccount=default:heketi-service-account"
   
- name: Create Secret
  shell: |
    kubectl create secret generic heketi-config-secret --from-file={{ gluster_dir }}/heketi.json
    while [ $(kubectl get secret heketi-config-secret | wc -l) == '0' ]; do
      echo -n .;
      sleep 1;
    done;

- name: Deploy Bootstrap
  shell: |
    kubectl create -f {{ gluster_dir }}/heketi-bootstrap.json
    while [ $(kubectl get deployment deploy-heketi | grep deploy-heketi | awk '{ print $5 }') == '0' ]; do
      echo -n .;
      sleep 1;
    done;

- name: Get Heketi Pod Name
  shell: "kubectl get pods | grep -i running | grep deploy-heketi | awk '{ print $1}'"
  register: heketi_pod_name

- name: Get Heketi Pod IP
  shell: "kubectl get pod {{ heketi_pod_name.stdout }} -o wide --no-headers=true -o wide | awk '{ print $6 }'"
  register: tmp
  when: heketi_pod_name.stdout != ""

- set_fact:
    heketi_pod_ip: '{{ tmp.stdout }}'
