---
# The inventory defines which hosts belong to which groups and what variables are applied to them. The playbooks
# themselves in our scheme do not define any variables. The names you see on the far left here correspond to the limit
# function you can run with the ansible-playbook command. For example ansible-playbook site.yml --limit sensor would
# look at this inventory file and see the hosts that are part of the sensor group. When site.yml imports the sensors.yml
# file, sensor.yml will only apply itself to the servers listed in the sensors group in this inventory file.

all:

  children:

    # Role specific breakout

    kubernetes:
      children:
        master-servers:

    bro:

    docker:
      children:
        sensors:
        servers:

    kibana:
      children:
        master-servers:

    portainer:
#      children:
#        master-servers:

    #haproxy:
    #  children:
    #    master-servers:

    elasticsearch:
      children:
        master-servers:

    logstash:
      children:
        master-servers:

    suricata:
#      children:
#        sensors:

    filebeat:
#      children:
#-        sensors:

    zookeeper:
#      children:
#        sensors:

    kafka:
#      children:
#        sensors:

    kubespray:
    #  hosts:
    #    localhost:
    #      ansible_hostname: 127.0.0.1
    #      ansible_connection: local

    harbor:
#      children:
#        master-servers:

    master-servers:

      hosts:
        rockserver1.lan:
          ansible_hostname: rockserver1.lan
          ansible_user: root
          ansible_connection: ssh

    nodes:

      children:

        sensors:

          vars:
            home_net: "[192.168.0.0/16,10.0.0.0/8,172.16.0.0/12]"

          hosts:
            rocksensor1.lan:
              ansible_hostname: rocksensor1.lan
              ansible_connection: ssh

        servers:

          hosts:
            rockserver3.lan:
              ansible_hostname: rocksecondary3.lan
              ansible_user: root
              ansible_connection: ssh
