---

- hosts: servers_secondary
# All variables are stored by group.  For example look in group_vars/servers/servers.yml

  # Common secondrary server roles are Elasticsearch, logstash, etc.
  roles:
    - common
    - docker
    - elasticsearch
    - logstash

...
