---

- hosts: servers
  roles:
    - common

    # Containerized_install: if true, all services are docker containers. Otherwise, services installed bare metal
    - { role: docker }

    - { role: elasticsearch, when: included_components.elasticsearch.enabled }
    - { role: logstash, when: included_components.logstash.enabled }
    - { role: kibana, when: included_components.kibana.enabled }
    #- { role: lighttpd, when: included_components['lighttpd'].enabled } #disabled for now, haproxy looks like a great replacement
    - { role: haproxy, when: included_components.haproxy.enabled }
    - { role: portainer, when: included_components.portainer.enabled }

    # Harbor must run last so that it uploads all containers installed on the machine.
    - { role: harbor, when: included_components.harbor.enabled }
