######################################################
################### Setup Zookeeper ##################
######################################################
---
-
  name: Install zookeeper service file
  copy:
    src: zookeeper.service
    dest: /etc/systemd/system/zookeeper.service
    mode: 0644
    owner: root
    group: root
  when: with_zookeeper

-
  name: Enable and start zookeeper
  service:
    name: zookeeper
    state: "{{ 'started' if enable_zookeeper else 'stopped' }}"
    enabled: "{{ enable_zookeeper }}"
  when: with_zookeeper