---
# tasks file for rocknsm.docket

# Install packages

# Ensure `stenographer` and `nginx` groups exists

# Configure docket app settings
- name: docket | ensure ansible_cache dir exists
  local_action: file path={{ ansible_cache }} state=directory mode=0700
  notify: docket | cleanup {{ ansible_cache }} dir

# TODO: this should probably
- name: docket | ensure rock nsm conf dir exists
  file:
    path: "{{ rocknsm_conf_dir }}"
    state: directory
    owner: "{{ rocknsm_conf_user }}"
    group: "{{ rocknsm_conf_group }}"

- name: docket | ensure docket x509 user exists
  user:
    name: "{{ docket_x509_user }}"
    state: present
  when: inventory_hostname in groups['docket']

- name: docket | ensure docket x509 group exists
  group:
    name: "{{ docket_x509_group }}"
    system: yes
    state: present
  when: inventory_hostname in groups['docket']

- name: docket | ensure docket x509 dir exists
  file:
    path: "{{ docket_x509_dir }}"
    state: directory
    mode:  0750
    owner:  "{{ docket_x509_user }}"
    group: "{{ docket_x509_group }}"
  when: inventory_hostname in groups['docket']


# Generate/copy x509 client cert/keys and CA certs
# Use new openssl module in ansible 2.3
- name: docket | create docket private key
  openssl_privatekey:
    path: "{{docket_x509_key}}"
    size: 4096
  when: inventory_hostname in groups['docket']

- name: docket | check for certificate
  stat:
    path: "{{docket_x509_dir}}/docket-{{inventory_hostname}}_sensor-{{item}}_cert.pem"
  register: docket_cert
  changed_when: false
  with_items: "{{ groups['stenographer'] }}"
  when: inventory_hostname in groups['docket']

- debug: var=docket_cert.results
  when: inventory_hostname in groups['docket']

- name: docket | create docket csr
  openssl_csr:
    path: "{{ docket_x509_key }}.csr"
    privatekey_path: "{{ docket_x509_key }}"
    commonName: "{{ docket_x509_cn }}"
    organizationName: "{{ docket_x509_o }}"
    countryName: "{{ docket_x509_c }}"
    keyUsage: digitalSignature
    extendedKeyUsage: clientAuth
  when:
    - inventory_hostname in groups['docket']
    - docket_cert|json_query('results[?stat.exists==`false`]')|length
  register: new_csr

- name: docket | fetch csr
  fetch:
    src: "{{docket_x509_key}}.csr"
    dest: "{{ ansible_cache }}/{{inventory_hostname}}.csr"
    flat: yes
  when:
    - inventory_hostname in groups['docket']
    - not new_csr|skipped

- debug:
    msg: "{{ hostvars[item].docket_cert|json_query('results[?stat.exists==`false`]')|length }}"
  when:
    - inventory_hostname in groups['stenographer']
  with_items:
    - "{{ groups['docket'] }}"

- debug:
    var: hostvars[item].docket_cert|json_query('results[?item==inventory_hostname]')
    #selectattr("item", "equalto", inventory_hostname)|map(attribute="stat.exists")|select("equalto", false)|list|length
  with_items:
    - "{{ groups['docket'] }}"
  when:
    - inventory_hostname in groups['stenographer']

- name: docket | push csr to stenographer hosts
  copy:
    src: "{{ansible_cache}}/{{hostvars[item].inventory_hostname}}.csr"
    dest: "{{steno_certs_dir}}/{{hostvars[item].inventory_hostname}}.csr"
  with_items:
    - "{{ groups['docket'] }}"
  when:
    - inventory_hostname in groups['stenographer']
    - hostvars[item].docket_cert.results|selectattr("item", "equalto", inventory_hostname)|map(attribute="stat.exists")|select("equalto",false)|list|length

- name: docket | sign certificate signing requests
  openssl_certificate:
    path: "{{steno_certs_dir}}/docket-{{hostvars[item].inventory_hostname}}_sensor-{{inventory_hostname}}_cert.pem"
    privatekey_path: "{{steno_ca_key}}"
    csr_path: "{{steno_certs_dir}}/{{hostvars[item].inventory_hostname}}.csr"
    provider: selfsigned
  with_items: "{{ groups['docket'] }}"
  when:
    - inventory_hostname in groups['stenographer']
    - hostvars[item].docket_cert.results|map(attribute="stat.exists")|select("equalto",false)|list|length

- name: docket | pull certificates back
  fetch:
    src: "{{steno_certs_dir}}/docket-{{hostvars[item].inventory_hostname}}_sensor-{{inventory_hostname}}_cert.pem"
    dest: "{{ansible_cache}}/docket-{{hostvars[item].inventory_hostname}}_sensor-{{inventory_hostname}}_cert.pem"
    flat: yes
  with_items: "{{ groups['docket'] }}"
  when:
    - inventory_hostname in groups['stenographer']
    - hostvars[item].docket_cert.results|map(attribute="stat.exists")|select("equalto",false)|list|length

- name: docket | pull back ca certificates
  fetch:
    src: "{{steno_ca_cert}}"
    dest: "{{ansible_cache}}/{{inventory_hostname}}_ca_cert.pem"
    flat: yes
  when:
    - inventory_hostname in groups['stenographer']

- name: docket | push certificates to docket hosts
  copy:
    src: "{{ansible_cache}}/docket-{{inventory_hostname}}_sensor-{{hostvars[item].inventory_hostname}}_cert.pem"
    dest: "{{docket_x509_dir}}/docket-{{inventory_hostname}}_sensor-{{hostvars[item].inventory_hostname}}_cert.pem"
  with_items: "{{ groups['stenographer'] }}"
  when:
    - inventory_hostname in groups['docket']
    - docket_cert.results|map(attribute="stat.exists")|select("equalto",false)|list|length

- name: docket | push stenographer ca certs
  copy:
    src: "{{ansible_cache}}/{{hostvars[item].inventory_hostname}}_ca_cert.pem"
    dest: "{{docket_x509_dir}}/{{hostvars[item].inventory_hostname}}_ca_cert.pem"
  with_items: "{{ groups['stenographer'] }}"
  when:
    - inventory_hostname in groups['docket']
