---
- name: docket | configure lighttpd + uwsgi
  template:
    src: docket_lighttpd_scgi.conf.j2
    dest: /etc/lighttpd/conf.d/docket_scgi.conf

- name: docket | configure lighttpd TLS listener
  template:
    src: docket_lighttpd_vhost.conf.j2
    dest: /etc/lighttpd/vhosts.d/docket.conf
  notify: docket | restart lighttpd

- name: docket | create vhost logdir
  file:
    state: directory
    path: "/var/log/lighttpd/{{ docket_web_server_name }}/"
    owner: lighttpd
    group: lighttpd
    mode: 0755
  
- name: docket | enable lighttpd vhosts
  lineinfile:
    path: /etc/lighttpd/lighttpd.conf
    regexp: '^#?\s*include.*vhosts\.d/.*$'
    line: include "/etc/lighttpd/vhosts.d/*.conf"
  notify: docket | restart lighttpd

- name: docket | enable lighttpd service
  service:
    name: lighttpd
    enabled: yes
  notify: docket | restart lighttpd
